version: "3.8"
services:
  ldap:
    container_name: contosoOpenLdap
    image: osixia/openldap:latest
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - ./ldap.env
    volumes:
      - ./ldap:/data/ldif
      - utags:/var/lib/ldap
      - ldap:/etc/ldap/slapd.d
volumes:
  utags:
  ldap:
